<?php require('template/header.phtml');

echo '<div class="col-md-12"><h2 class="text-center">' . $view->pageTitle . '</h2></div>';

if (isset($_SESSION["login"])) {
    echo'
    <div class="row add-member">
        <div class="col-md-6"></div>
        <div class="col">
            <form class="form-inline" method="post" action="/members.php?id=' . $_GET['id'] .'">
              <input class="form-control" type="text" placeholder="E-mail" name="email">
              <button class="form-control btn-primary btn-sm" type="submit" name="addMember">Add User</button>
            </form>
        </div>
    </div>';

    echo '
    <div class="container" id="membercontainer">
        <div class="row" id="topmember">
            <div class="col-md-2 col-sm-2"></div>
            <div class="col-md-2 col-sm-2" id="permission-name">Username</div>
            <div class="col-md-1 col-sm-1" id="permission-name">Modify Products</div>
            <div class="col-md-1 col-sm-1" id="permission-name">Add/Remove Users</div>
            <div class="col-md-1 col-sm-1" id="permission-name">Modify Rights</div>
            <div class="col-md-1 col-sm-1" id="permission-name">View Logs</div>
        </div>
        ';

    //Preview Users
    $owner = $view->vendor->getCreatorId();

    foreach ($view->membersDataSet as $memberData) {
        echo'
        <div class="row" id="memberentry">
            <div class="col-md-2"></div>
            <div class="col-md-2" id="memberuser">'. $memberData->getEmail() .'</div>';

        if($memberData->getUID() == $owner) {
            echo '
            <div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled" checked disabled></div>
            <div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled" checked disabled></div>
            <div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled" checked disabled></div>
            <div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled" checked disabled></div>
        </div>';
        }elseif ($memberData->getEmail() == $_SESSION["login"]){
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled"'; if($memberData->getProducts() == 1){echo 'checked';} echo' disabled></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled"'; if($memberData->getUsers() == 1){echo 'checked';} echo' disabled></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled"'; if($memberData->getRights() == 1){echo 'checked';} echo' disabled></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" id="flexCheckDisabled"'; if($memberData->getLogs() == 1){echo 'checked';} echo' disabled></div>';
        echo'</div>';
        }else{
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" name="permission'.$memberData->getUID().'[]" value="products" id="flexCheck"'; if($memberData->getProducts() == 1){echo 'checked';} echo'></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" name="permission'.$memberData->getUID().'[]" value="users" id="flexCheck"'; if($memberData->getUsers() == 1){echo 'checked';} echo'></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" name="permission'.$memberData->getUID().'[]" value="rights" id="flexCheck"'; if($memberData->getRights() == 1){echo 'checked';} echo'></div>';
            echo '<div class="col-md-1" id="permission-name"><input class="form-check-input" type="checkbox" name="permission'.$memberData->getUID().'[]" value="logs" id="flexCheck"'; if($memberData->getLogs() == 1){echo 'checked';} echo'></div>';
            echo '<div class="col-md-2" id="permission-name"><a class="btn btn-danger btn-sm" href="" role="button">Remove User</a></div>';
        echo'</div>';
        }
    }

    echo '
        <div class="row" id="change-buttons">
            <div class="col-md-4"></div>
            <div class="col-md-3">
                <form class="form-inline" method="post" action="/members.php?id=' . $_GET['id'] .'">
                  <button class="form-control btn-success btn-sm" type="submit" name="savePermissions">Save Changes</button>
                </form>
            </div>
        </div>
    </div>';

}
else {
    echo 'Access Denied';
}
require('template/footer.phtml');
