<?php require('template/header.phtml');

if (isset($_SESSION["login"])) { //Don't show register page if user is registered
    echo '
    <div class="container" id="vendorcontainer">
        <div class="row" id="topvendor">
            <div class="col-md-2" id="vendorbar">Vendor</div>
            <div class="col-md-2" id="vendorbar">Amount of Products</div>
            <div class="col-md-2" id="vendorbar"><a class="btn btn-primary btn-sm" href="/create-vendor.php" role="button">Create New</a></div> 
        </div>
        ';

    foreach ($view->vendorDataSet as $vendorData) {
        echo'
        <div class="row" id="vendorentry">
            <div class="col-md-2">'.$vendorData->getName().'</div>
            <div class="col-md-2"><b>5</b></div>
            <div class="col-md-2"><a class="btn btn-default btn-sm" href="/view-vendor.php" role="button">View</a></div> 
        </div> 
        </div>
    ';

    echo '</div>';
    }


}
else {
    echo 'Login to access your vendors!';
}
require('template/footer.phtml');
