<?php require('template/header.phtml');

echo '<h1 class="text-center">Welcome to the Fanatics Vendor Portal - ' . $view->pageTitle . '</h1>';

if (isset($_SESSION["login"])) { //Don't show register page if user is registered
    echo '
        <table class="table">
          <thead>
            <tr>
              <th scope="col" class="text-center">Vendor Name</th>
              <th scope="col" class="text-center">Amount of Products</th>
              <th scope="col" class="text-center">Total Product Value</th>
              <th scope="col" class="text-center"><a class="btn btn-primary btn-sm" href="/add-vendor.php" role="button">Create Vendor</a></th>
            </tr>
          </thead>
        ';

    foreach ($view->vendorDataSet as $vendorData) {
        echo'
        <tr>
            <td class="text-center">'.$vendorData->getName().'</td>
            <td class="text-center"><b>'. $view->productDataSet->fetchAmount($vendorData->getID()) .'</b></td>
            <td class="text-center"><b>£'. $view->productDataSet->fetchValue($vendorData->getID()) .'</b></td>
            <td class="text-center"><a class="btn btn-default btn-sm" href="/view-vendor.php?id='.$vendorData->getID().'" role="button">View Vendor Dashboard</a></td>
        </tr>
    ';
    }
    echo '</table>';
}
else {
    echo '<h3 class="text-center">Log in to view this page.</h3>';
}

require('template/footer.phtml');
