<?php require('template/header.phtml');

echo '<h1 class="text-center">Welcome to the Fanatics Vendor Portal - ' . $view->pageTitle . '</h1>';

if (isset($_SESSION["login"])) { //Don't show register page if user is registered
    echo '
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Vendor Name</th>
              <th scope="col">Amount of Products</th>
              <th scope="col"><a class="btn btn-primary btn-sm" href="/create-vendor.php" role="button">Create Vendor</a></th>
            </tr>
          </thead>
        ';

    foreach ($view->vendorDataSet as $vendorData) {
        echo'
        <tr>
            <td>'.$vendorData->getName().'</td>
            <td><b>'.$view->productDataSet.'</b></td>
            <td><a class="btn btn-default btn-sm" href="/view-vendor.php?id='.$vendorData->getID().'" role="button">View Vendor Dashboard</a></td>
        </tr>
    ';
    }
    echo '</table>';
}
else {
    echo '<h3 class="text-center">Log in to view this page.</h3>';
}

require('template/footer.phtml');
