<?php require('template/header.phtml');

echo '<h1 class="text-center">Welcome to the Fanatics Vendor Portal - ' . $view->pageTitle . '</h1>';

if (isset($_SESSION["login"])) {
    $permissions = $view->vendor->getUserPermissions($_SESSION["login"]);

    echo '
    <table class="table">
          <thead>
            <tr>
              <th scope="col" class="text-center"></th>
              <th scope="col" class="text-center"></th>
              <th scope="col" class="text-center"></th>
              <th scope="col" class="text-center"></th>
            </tr>
          </thead>
          <tr>
          <td><a class="btn btn-default btn-sm" href="/members.php?id=' . $_GET['id'] .'" role="button">Add/Remove Users</a></td>
          <td><a class="btn btn-default btn-sm" href="/add-product.php?id='. $_GET['id'] .'" role="button">Add Product</a></td>
          <td><a class="btn btn-default btn-sm" href="/view-products.php?id=' . $_GET['id'] .'" role="button">View Products</a></td>
          <td><a class="btn btn-default btn-sm" href="" role="button">View Logs</a></td>
</tr>
        </table>
    ';
}
require('template/footer.phtml');
