    </div>

    <footer class="note col-md-12">
        <div>
            Copyright © 2022 Fanatics Inc. All Rights Reserved
        </div>
    </footer>
    </body>
    </html>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>