<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">

    <title>Fanatics Vendor Portal - <?php echo $view->pageTitle; ?></title>
</head>
<body role=""document">
<div class="container-fluid">
        <div  class="row">
            <div class="col-xs-3">

            </div>
        </div>


    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
        <ul class="nav navbar_default nav-stacked">
            <img class="nav-justified" src="images/fanatics-logo.png" alt="Fanatics Logo" />
            <?php if (isset($_SESSION['login'])){
                echo '<h4 class="text-center">Hello '. $_SESSION['login'] . '</h4>';
            }?>
        </ul>
            <?php

            if (!isset($_SESSION["login"])) {
                echo ' 
            <form method="post" action="" class="form-content">
                <input class="form-control" type="text" name="email" placeholder="Email">
                <input class="form-control" type="password" name="password" placeholder="Password">
                <input class="form-control" type="submit" name="loginButton" value="Login">
            </form>
            <li><a href="index.php">Home</a></li>
            <li><a href="register.php">Register</a></li>';
            }
            else {
            echo '
            <form method="post" action="" class="form-content">
                <input class="form-control" type="submit" name="logoutButton" value="Logout">
            </form>
            <li><a href="index.php">Home</a></li>
            <li><a href="vendors.php">Vendors</a></li>';
            if ($view->pageTitle == 'My Products' || $view->pageTitle == 'Add Product' || $view->pageTitle == 'Members' || $view->pageTitle == 'Logs'){
                echo '<li><a href="view-vendor.php?id=' . $_GET['id'] . '">Back to dashboard</a></li>';
            }
            }
            ?>

        </ul>
       </div>

        <div id="content" class="col-xs-6 col-sm-9 col-md-10">



